[package]
name = "devices"
version = "0.0.0"
edition = "2021"
description = "A simple cross-platform library for retrieving information about connected devices."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/devices"